server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    hostname: gateway-service
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      routes:
        - id: pricing-service
          uri: lb://PRICING-SERVICE
          predicates:
            - Path=/api/pricing/**
          filters:
        - id: group-discount-service
          uri: lb://GROUP-DISCOUNT-SERVICE
          predicates:
            - Path=/group-discount/**
          filters:
        - id: loyalty-service
          uri: lb://LOYALTY-SERVICE
          predicates:
            - Path=/loyalty/**
          filters:
        - id: specialday-service
          uri: lb://SPECIALDAY-SERVICE
          predicates:
            - Path=/api/special-pricing/**
          filters:
        - id: booking_service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**
          filters:
        - id: kart_service
          uri: lb://KART-SERVICE
          predicates:
            - Path=/api/kart/**
          filters:
        - id: rack_service
          uri: lb://RACK-SERVICE
          predicates:
            - Path=/api/rack/**
          filters:
        - id: report_service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/reports/**
          filters:
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
