server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      routes:
        - id: pricing-service
          uri: lb://pricing-service:8091
          predicates:
            - Path=/api/pricing/**
          filters:
            - StripPrefix=1
        - id: test-route
          uri: lb://pricing-service  # Nombre registrado en Eureka
          predicates:
            - Path=/test
          filters:
            - StripPrefix=0  # No elimina ningún segmento de la ruta
