server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      routes:
        - id: pricing-service
          uri: lb://pricing-service
          predicates:
            - Path=/api/pricing/**
          filters:
            - StripPrefix=1
        - id: group-discount-service
          uri: lb://group-discount-service
          predicates:
            - Path=/group-discount/**
          filters:
            - StripPrefix=1
        - id: loyalty-service
          uri: lb://loyalty-service
          predicates:
            - Path=/loyalty/**
          filters:
            - StripPrefix=1
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
