server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pricing-service
          uri: lb://PRICING-SERVICE  # "lb" = load balancing
          predicates:
            - Path=/api/pricing/**
          filters:
            - StripPrefix=1  # Elimina "/api/pricing" al redirigir
